labeler-strategy: append

css:
  - files:
    - css/**
html:
  - files:
    - html/**
js:
  - files:
    - js/**
tools:
  - files:
    - tools/**
a11y:
  - files:
    - a11y/**
'рецепт':
  - files:
    - recipes/**
'кухня':
  - files:
    - .github/**
    - docs/**
    - pages/**
    - settings/**
    - specials/**
    - CHANGELOG.md
    - CODEOWNERS
    - LICENSE-ND.md
    - LICENSE-SA.md
    - README.md
    - new.sh
    - start.sh
'улучшение':
  - files:
    - modified:
      - css/**/*.md
      - html/**/*.md
      - js/**/*.md
      - tools/**/*.md
      - a11y/**/*.md
      - recipes/**/*.md
      - people/**/index.md
    - removed:
      - css/**/*.md
      - html/**/*.md
      - js/**/*.md
      - tools/**/*.md
      - a11y/**/*.md
      - recipes/**/*.md
      - people/**/index.md
    - renamed:
      - css/**/*.md
      - html/**/*.md
      - js/**/*.md
      - tools/**/*.md
      - a11y/**/*.md
      - recipes/**/*.md
      - people/**/index.md
'демо':
  - files:
    - modified:
      - css/**/demos/**/*.html
      - html/**/demos/**/*.html
      - js/**/demos/**/*.html
      - tools/**/demos/**/*.html
      - a11y/**/demos/**/*.html
      - recipes/**/demos/**/*.html
    - removed:
      - css/**/demos/**/*.html
      - html/**/demos/**/*.html
      - js/**/demos/**/*.html
      - tools/**/demos/**/*.html
      - a11y/**/demos/**/*.html
      - recipes/**/demos/**/*.html
    - renamed:
      - css/**/demos/**/*.html
      - html/**/demos/**/*.html
      - js/**/demos/**/*.html
      - tools/**/demos/**/*.html
      - a11y/**/demos/**/*.html
      - recipes/**/demos/**/*.html
'дока':
  - files:
    - added:
      - css/**/index.md
      - html/**/index.md
      - js/**/index.md
      - tools/**/index.md
      - a11y/**/index.md
      - recipes/**/index.md
  - meta:
    - tags:
      - doka
'статья':
  - files:
    - added:
      - css/**/index.md
      - html/**/index.md
      - js/**/index.md
      - tools/**/index.md
      - a11y/**/index.md
      - recipes/**/index.md
  - meta:
    - tags:
      - article
placeholder:
  - files:
    - added:
      - css/**/index.md
      - html/**/index.md
      - js/**/index.md
      - tools/**/index.md
      - a11y/**/index.md
      - recipes/**/index.md
  - meta:
    - tags:
      - placeholder
